In [17]:
import pandas as pd
import numpy as np

s1:pd.Series = pd.Series([1,2,3,3,6])

print(s1.index)
print(s1)
s1.array

print(s1[s1 > 3])
print(s1 * 2)



RangeIndex(start=0, stop=5, step=1)
0    1
1    2
2    3
3    3
4    6
dtype: int64
4    6
dtype: int64
0     2
1     4
2     6
3     6
4    12
dtype: int64


In [5]:
s1:pd.Series = pd.Series((61,2,3,3,))
print(s1)

0    61
1     2
2     3
3     3
dtype: int64


In [6]:
s1:pd.Series = pd.Series({"name": "saleem", "fname": "Ghulam", "roll_no": "1233"})
print(s1)

name       saleem
fname      Ghulam
roll_no      1233
dtype: object


In [7]:
list1:list[str] = ["q", "b", "f", "e"]
index1:list[int] = [4,2,3,5]

s2:pd.Series = pd.Series(list1, index=index1)
s2

4    q
2    b
3    f
5    e
dtype: object

In [8]:

import pandas as pd

indexes:list[list[str]] = [['a', 'a', 'b', 'b', 'b'],
                          ['a', 'b', 'c', 'f', 'h'],
                          ['a', 'b', 'c', 'f', 'h'],
                          ['a', 'b', 'c', 'f', 'h']]
values:list[int] = [1,2,3,4,5]


s3:pd.Series = pd.Series(values, index=indexes)

s3

a  a  a  a    1
   b  b  b    2
b  c  c  c    3
   f  f  f    4
   h  h  h    5
dtype: int64

In [9]:
import pandas as pd

indexes:list[list[str]] = [['a', 'a', 'b', 'b', 'b'],
                          ['a', 'b', 'c', 'f', 'h'],
                          ['a', 'b', 'c', 'f', 'h'],
                          ['a', 'b', 'c', 'f', 'h']]

values:list[int] = [1,2,3,4]


s3:pd.Series = pd.Series(indexes, index=values)

s3

1    [a, a, b, b, b]
2    [a, b, c, f, h]
3    [a, b, c, f, h]
4    [a, b, c, f, h]
dtype: object

In [10]:

sdata:dict[str, int] = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3:pd.Series = pd.Series(sdata)

states:list[str] = ["California", "Ohio", "Oregon", "Texas"]

obj3 = pd.Series(sdata, index=states)


#pd.notna(obj3)
obj3.isna()


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [11]:

sdata:dict[str, int] = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3:pd.Series = pd.Series(sdata)

states:list[str] = ["Ohio", "Oregon", "Texas"]

obj3 = pd.Series(sdata, index=states, name="saleem data")


#pd.notna(obj3)
obj3.isna()
obj3

Ohio      35000
Oregon    16000
Texas     71000
Name: saleem data, dtype: int64

In [12]:
x = 5
while x >0:
    x-=1

print(x)

0


In [14]:
print(pd.Index(["foo", "foo", "bar", "bar"]))


Index(['foo', 'foo', 'bar', 'bar'], dtype='object')


In [23]:
import pandas as pd
import numpy as np




In [28]:
obj = pd.Series(["blue", "green", "red"], index=[0,4,7])
rendex= obj.reindex(np.arange(10), method="ffill")
rendex

0     blue
1     blue
2     blue
3     blue
4    green
5    green
6    green
7      red
8      red
9      red
dtype: object

In [63]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), 
                     index=["Ohio", "Colorado", "Utah"], 
                     columns=["one", "two", "three"])
print(frame)


print("-----------------------")
state = ["caps", "source", "thrice","fist", "second", "third"]
frame2= frame.reindex(index=[1,2,3,4], columns= state )

print(frame2)

          one  two  three
Ohio        0    1      2
Colorado    3    4      5
Utah        6    7      8
          one  two  three
Ohio        0    1      2
Colorado    3    4      5
Utah        6    7      8
-----------------------
   caps  source  thrice  fist  second  third
1   NaN     NaN     NaN   NaN     NaN    NaN
2   NaN     NaN     NaN   NaN     NaN    NaN
3   NaN     NaN     NaN   NaN     NaN    NaN
4   NaN     NaN     NaN   NaN     NaN    NaN


In [76]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), 
                     index=["Ohio", "Colorado", "Utah"], 
                     columns=["one", "two", "three"])
print(frame)
print("----------------")

data = frame.drop(index=["Ohio", "Colorado"])
data1 = frame.drop(["one"], axis="columns")

print(data)


print("----------------")
print(data1)

          one  two  three
Ohio        0    1      2
Colorado    3    4      5
Utah        6    7      8
----------------
      one  two  three
Utah    6    7      8
----------------
          two  three
Ohio        1      2
Colorado    4      5
Utah        7      8


In [79]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                                 columns=list("bde"),
                                 index=["Utah", "Ohio", "Texas", "Oregon"])



np.abs(frame)

b         d         e
Utah    1.750172  0.297848  0.156259
Ohio    0.631958  1.546587  0.428664
Texas   0.372579  0.069942  1.181978
Oregon  0.636177  0.495053  0.698227

In [81]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                                 columns=list("bde"),
                                 index=["Utah", "Ohio", "Texas", "Oregon"])



np.abs(frame)




def f1(x):
    return x.max() - x.min()

frame.apply(f1)



b    2.632968
d    1.508132
e    2.779346
dtype: float64

In [ ]:
name = "saleem"
print(name.upper())

[i for i in dir(name) if "_" not in i]

In [13]:
name1 :str = 20000
print(name1)

20000


In [17]:
func: tuple[str, int , float] = ("pakistan", 2, 2.0)

func

('pakistan', 2, 2.0)

In [29]:
name : str = 'saleem'
age:int = 43

print("My name is %s and my age is %d" %(name, age))

My name is saleem and my age is 43


In [30]:
name : str = 'saleem'
age:int = 43

print("My name is {} and my age is {}".format(name, age))

My name is saleem and my age is 43


In [36]:
name : str = 'saleem'
age:int = 43

print(f"My name is {name} and my age is {age}")

My name is saleem and my age is 43


In [ ]:
name : str = 'saleem'
age:int = 43

print(f'''My name is 
      {name} 
      and my age is 
      {age}''')

In [41]:
my_name : str = 'saleem'
my_age:int = 43

print(f'''My name is 
      {my_name} 
      and my age is 
      {my_age}''')

My name is 
      saleem 
      and my age is 
      43


In [42]:
name: str = 'My name is salemm \n father's name'

SyntaxError: unterminated string literal (detected at line 1) (1991690063.py, line 1)

In [47]:
name: str = "My name is salemm\n father's name"
name

"My name is salemm\n father's name"

In [46]:
name: str = "My name is salemm\n father's name"
print(name)

My name is salemm
 father's name


In [50]:
name: str = 'My name is salemm\n father\'s name'
print(name)

My name is salemm
 father's name


In [48]:
name: str = 'My name is "salemm"\n father name'
print(name)

My name is "salemm"
 father name


In [51]:
"a" + "b" + "c"

'abc'

In [54]:
"a" + "7"

'a7'

In [60]:
name : str = "saleem"
fname:str = "GM"
age:int = 23

print("My name is : " + name + "\n MY father name is : " + fname + "/n age is : " + str(age))

My name is : saleem
 MY father name is : GM/n age is : 23


In [61]:
name : str = "saleem"
fname:str = "GM"
age:int = 23

print("My name is : " + name + "\n MY father name is : " + fname + "/n age is : " + age)


TypeError: can only concatenate str (not "int") to str

In [63]:
print(2+\
      8 +\
        7)

17


In [75]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

print("PIAIC Students:\nstudent name :" + name+\
      " \nage: " + str(age)\
        +"\neducaion : " + education)

PIAIC Students:
student name :saleem 
age: 30
educaion : MA in Arts


In [77]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

print('''PIAIC Students:
    student name :{name}
    age:{age}
    educaion : {education} ''')

PIAIC Students:
    student name :{name}
    age:{age}
    educaion : {education} 


In [80]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

print(f'''PIAIC Students:
    student name :{name}
    age:{age}
    educaion : {education} 

Total = {2 + 4+6}

''')

PIAIC Students:
    student name :saleem
    age:30
    educaion : MA in Arts 

Total = 12




In [85]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

print("""PIAIC Students:
    student name :{{name}}
    age:{{age}}
    educaion : {{education}}



""")

PIAIC Students:
    student name :{{name}}
    age:{{age}}
    educaion : {{education}}






In [87]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

card: str= f"""PIAIC Students:
    student name :{name}
    age:{age}
    educaion : {education}
"""

print(card)

PIAIC Students:
    student name :saleem
    age:30
    educaion : MA in Arts



In [92]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

card: str = """
PIAIC Students:
student name :%s
age:%d
educaion : %s 
""" %(name, age, education )

print(card)


PIAIC Students:
student name :saleem
age:30
educaion : MA in Arts 



In [94]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

card: str= """PIAIC Students:
    student name :{}
    age:{}
    educaion : {}
""".format(name, age, education )

print(card)

PIAIC Students:
    student name :saleem
    age:30
    educaion : MA in Arts



In [96]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

card: str= """PIAIC Students:
    student name :{1}
    age:{2}
    educaion : {0}
""".format(education ,name, age)

print(card)

PIAIC Students:
    student name :saleem
    age:30
    educaion : MA in Arts



In [40]:
name : str = "saleem"
education:str = "MA in Arts"
age:int = 30

card: str= """PIAIC Students:
    student name :{b}
    age:{c}
    educaion : {a}
""".format(a= education ,b=name, c = age)

print(card)

PIAIC Students:
    student name :saleem
    age:30
    educaion : MA in Arts



In [32]:
import re

name : str = "      Muhammad                 saleem         Akhtar          "

display(name.lstrip())
display(name.rstrip())
display(name.strip())

name1 : str = re.sub(' {2,50}', " ", name).strip()
print(name1)

'Muhammad                 saleem         Akhtar          '

'      Muhammad                 saleem         Akhtar'

'Muhammad                 saleem         Akhtar'

Muhammad saleem Akhtar


In [29]:
nostarch_url:str = 'https://nostarch.com'
nostarch_url.removeprefix("https://")

'nostarch.com'

In [ ]:
names: list[str] = [chr(i) for i in range(65,91)]
names

In [46]:
a, b, c = ('qasim', 7, 3.0)
print(a)
print(b)
print(c)

qasim
7
3.0


In [47]:
a, b, c = ['qasim', 7, 3.0]
print(a)
print(b)
print(c)

qasim
7
3.0


In [52]:
print(ord("b"))
print(ord("B"))

print(chr(98))
print(chr(66))

98
66
b
B


#  -------------------------------------------           List

In [56]:
name = ["aslam", "hamza", "rumaisa", 20, True, 10,20]

print(name)

['aslam', 'hamza', 'rumaisa', 20, True, 10, 20]


In [58]:
name:list[str| int| bool| float]= ["aslam", "hamza", "rumaisa", 20, True, 10,20]

print(name)

['aslam', 'hamza', 'rumaisa', 20, True, 10, 20]


In [60]:
name:list[str| int| bool|float]= ["aslam", "hamza", "rumaisa", 20, True, 10.20]

print(name)
print(type(name))

['aslam', 'hamza', 'rumaisa', 20, True, 10.2]
<class 'list'>


In [59]:
from typing import Any

name:list[Any]= ["aslam", "hamza", "rumaisa", 20, True, 10.20]

print(name)

['aslam', 'hamza', 'rumaisa', 20, True, 10.2]


In [62]:
liststr : list[str] = ["annnnnnhhtuocnjiuhv"]
display(liststr)

['annnnnnhhtuocnjiuhv']

In [64]:
liststr : list[str] = list("anvbfd")
display(liststr)

['a', 'n', 'v', 'b', 'f', 'd']

In [69]:


dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [73]:
help("reverse")

No Python documentation found for 'reverse'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [76]:
names : list[str] = ['a','b','c','d']

print(names)

names.insert(0,"Qasim") # insert on perticular postion

print(names)

['a', 'b', 'c', 'd']
['Qasim', 'a', 'b', 'c', 'd']


In [1]:
data_base : list[tuple[str,str]] = [("qasim",'123'),
                                    ("sirzia",'345'),
                                    ('ikhlas','789')
                                    ]
input_user : str = input("Enter user name")
input_password : str = input("Enter user password")



for row in data_base:
    user, password = row
    if input_user == user and input_password == password:
        print(f"Valid User {user}")
        break
else:
    print("Not found or Invalid user name")

Valid User qasim


In [6]:
names:list[str] = ['Sir Zia', "Muhammad Qasim", "DR Noman"]

for i in names:
    print(i)
   
else:
    print("Hello world")

Sir Zia
Muhammad Qasim
DR Noman
Hello world


In [9]:
names: list[str] = [ "DR Noman", 'Sir Zia', "Muhammad Qasim"]

for i in names:
    
    print(i)
else:
    print("Hello world")


DR Noman
Sir Zia
Muhammad Qasim
Hello world


In [13]:
magicians = ['alice', 'david', 'carolina']

list(enumerate(magicians))


[(0, 'alice'), (1, 'david'), (2, 'carolina')]

In [17]:
my_foods = ['pizza', 'falafel', 'carrot cake'] 
friend_foods = my_foods[:]# deep copy

print(my_foods)
print(friend_foods)

friend_foods[0] = "Tikka"

print(my_foods)
print(friend_foods)

['pizza', 'falafel', 'carrot cake']
['pizza', 'falafel', 'carrot cake']
['pizza', 'falafel', 'carrot cake']
['Tikka', 'falafel', 'carrot cake']


In [23]:
cars : list[str] = ['audi', 'bmw', 'subaru', 'toyota']

[i.upper() if i=='bmw' else i.title() for i in cars]

['Audi', 'BMW', 'Subaru', 'Toyota']

In [26]:
data: set = {7, 1, 2, 1, 1, 1, 1, 3, 2}

# Convert the set to a list to access elements by index
data_list = list(data)
print(data_list)
# Access the first element (unique in a set, but order is not guaranteed)
print(data_list[3])


[1, 2, 3, 7]
7


In [5]:
#                     
l1 : list[set[int]] = list({1,2,3,4,1,1,1,1})

for k in l1:
    print(f"value from list of set : {k} ")

value from list of set : 1 
value from list of set : 2 
value from list of set : 3 
value from list of set : 4 


In [8]:
data : list[dict[str,str]] = []

flag : bool = True

while flag:
    print("write quite or exit to stop this program")
    name : str = input ("Your good name ? \t:")
    eduction: str = input("Your last education? \t")

    if name in ['exit','quite','close','stop'] or eduction  in ['exit','quite','close','stop']:
        flag=False
        break
    data.append({"name":name,
                 "education": eduction})

display(data)

write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program
write quite or exit to stop this program


[{'name': 'a', 'education': 'f'},
 {'name': 'c', 'education': 'b'},
 {'name': 'g', 'education': 'g'},
 {'name': 'g', 'education': 'y'},
 {'name': 'u', 'education': 'i'},
 {'name': 'f', 'education': 'j'},
 {'name': 'v', 'education': 'n'},
 {'name': 't', 'education': 'u'}]

In [10]:
a = 10

while a:
    print("abc")
    break

NameError: name 'b' is not defined

In [14]:
result: int = len("Hello World!")
print(result)  # Output: 12

12


In [17]:
from typing import Callable

square: Callable[[int], int] = lambda x: x * x
print(type(square))



square(5)
dir(square)

<class 'function'>


['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__type_params__']

"""
Factorial Function Call (factorial(5)):

n is 5, which is not equal to 0.
The else branch is executed, and it returns 5 * factorial(4).
Nested Factorial Function Call (factorial(4)):

n is 4, which is not equal to 0.
The else branch is executed, and it returns 4 * factorial(3).
Nested Factorial Function Call (factorial(3)):

n is 3, which is not equal to 0.
The else branch is executed, and it returns 3 * factorial(2).
Nested Factorial Function Call (factorial(2)):

n is 2, which is not equal to 0.
The else branch is executed, and it returns 2 * factorial(1).
Nested Factorial Function Call (factorial(1)):

n is 1, which is not equal to 0.
The else branch is executed, and it returns 1 * factorial(0).
Nested Factorial Function Call (factorial(0)):

n is 0.
The base case is triggered, and it returns 1.
Now, the recursive calls start to unwind:

factorial(1) returns 1 * 1 = 1.
factorial(2) returns 2 * 1 = 2.
factorial(3) returns 3 * 2 = 6.
factorial(4) returns 4 * 6 = 24.
factorial(5) returns 5 * 24 = 120.
"""

In [1]:

from typing import Callable

add:Callable[[int, int], int] = lambda x, y: x + y

print(add(3,4))



7


In [4]:
data = [1,2,3,4,5,6,7,8,9,10]

data = list(filter(lambda x:x%2==0 ,data))

data

[2, 4, 6, 8, 10]

In [13]:
from collections.abc import Iterator

def my_range(start:int, end:int, step:int)->Iterator[int]:
    for i in range(start, end+1, step):
        yield i

my_fun:Iterator[int] = my_range(1,11, 1)
print(my_fun)
print(next(my_fun))
print(next(my_fun))
print("------------------------------")

print(list(my_fun))



<generator object my_range at 0x0000020E5566AF20>
1
2
------------------------------
[3, 4, 5, 6, 7, 8, 9, 10, 11]


In [12]:
from typing import Tuple

def my_greet(*names)->None:
    for name in names:
        print("Hello dear", name)

my_greet("Monica", "Luke", "Steve", "John","Sir Zia", "Muhammad Qasim")  

Hello dear Monica
Hello dear Luke
Hello dear Steve
Hello dear John
Hello dear Sir Zia
Hello dear Muhammad Qasim


In [25]:
from typing import Tuple

def greet(*names) -> None:
    """
    This function greets all persons in the names tuple.
    """
    for name in names:
        print("Hello", name)

greet("Monica", "Luke", "Steve", "John","Sir Zia", "Muhammad Qasim")

Hello Monica
Hello Luke
Hello Steve
Hello John
Hello Sir Zia
Hello Muhammad Qasim


In [31]:



def greet(**xyz)->None:
    print(xyz)


greet(a = "saleem", b = "ahmad") 


{'a': 'saleem', 'b': 'ahmad'}


In [32]:
def modify_list(lst: list):
    print("Inside function (before modification):", id(lst))
    lst.append(4)
    print("Inside function (after modification):", id(lst))

my_list = [1, 2, 3]
print("Before function call:", id(my_list))
modify_list(my_list)
print("After function call:", id(my_list))

Before function call: 2260587385984
Inside function (before modification): 2260587385984
Inside function (after modification): 2260587385984
After function call: 2260587385984


In [40]:
try:
    my_list = [1, 2, 3]
    print(my_list[3])  # This will raise an IndexError
except IndexError as e:
    print(e)

list index out of range


In [44]:
try:
    numerator = 10
    denominator = 5
    result = numerator / denominator
except ZeroDivisionError as e:
    print("Caught a ZeroDivisionError:", str(e))
else:
    print("Division successful:", result)
finally:
    print("This block is always executed")

Division successful: 2.0
This block is always executed


In [48]:
a : list[str] = ['a','b'] # mutable
b : list[str] = ['c','d'] # mutable

print(id(a))
print(id(b))

c = a + b
print(c)
print(id(c))


2260604893696
2260604895040
['a', 'b', 'c', 'd']
2260604417088


In [51]:
num_a:int = 5
print(id(num_a))
num_b = num_a
print(id(num_b))
num_a = num_a + 1
print(id(num_a))
print("num_b:", num_b) # Output: num_b: 5
print("num_a:", num_a)

140715754801720
140715754801720
140715754801752
num_b: 5
num_a: 6


In [54]:
print("logic1")
print("logic2")

l1 : list[int] = [1,2,3]

try:
    print(5/2)
    print(l1[0])
    
    open("aa.txt")
except (ZeroDivisionError):
    print("Zerro Division Error!")
except IndexError:
    print("Index Error")
except NameError:
    print("Name not defined")
except:
    print("Some thing is wrong!")


print("logic4")
print("logic5")

logic1
logic2
2.5
1
Some thing is wrong!
logic4
logic5


# OOP Concepts

In [7]:
class MYCar:

    '''the purpose of this class is to show the specs of class'''
    # constructor /method   
    def __init__(self, color:str, modal:int) -> None:
        # instance variable
        self.color:str = color 
        # instance variable
        self.modal:int = modal
        
    # instance methods
    def brak(self)->None:
        print(f"My car has {self.color} Color and modal is {self.modal}")


suzuki:MYCar = MYCar("silver", 2019)#  constructor is used to initialized the object and memory is allocated
suzuki.brak()


# builtin functions of class
print(MYCar.__dict__)# about class all methods and attributes
print(MYCar.__name__)# name of class
print(MYCar.__module__)# in which module class is present
print(MYCar.__doc__)
print(isinstance(suzuki, MYCar)) # it will check suzuki obj is in class Mycar & it will return true or false, 


My car has silver Color and modal is 2019
{'__module__': '__main__', '__doc__': 'the purpose of this class is to show the specs of class', '__init__': <function MYCar.__init__ at 0x000001E029D8E0C0>, 'brak': <function MYCar.brak at 0x000001E029D8E160>, '__dict__': <attribute '__dict__' of 'MYCar' objects>, '__weakref__': <attribute '__weakref__' of 'MYCar' objects>}
MYCar
__main__
the purpose of this class is to show the specs of class
True


In [8]:
print(MYCar.__name__)

MYCar


In [24]:
class MYCar:
    '''the purpose of this class is to show the specs of class'''

    # class variable
    engine_no = 1235555

    # constructor /method   
    def __init__(self, color:str, modal:int) -> None:
        # instance variable
        self.color:str = color 
        # instance variable
        self.modal:int = modal
        
    # instance methods
    def brak(self)->None:
        print(f"My car has {self.color} Color and modal is {self.modal}")

    # class variable are modified in class method
    @classmethod  # decorator is used to represent the class method
    def cls_engine_no(cls):
        state = cls.engine_no = 333333333333
        return state

suzuki:MYCar = MYCar("silver", 2019)   # constructor is used to initialized the object and memory is allocated
suzuki.brak()
print(suzuki.engine_no) # class variable can be accessed by object reference but not modified
print(MYCar.engine_no) # class variable can also  be accessed by class reference also modified

MYCar.engine_no = 1111111111  # class variable is modified by class refrence or class method only
print(MYCar.engine_no)

suzuki.engine_no  = 37777777  # object ref will not modify the class variable but creates new instance variable
print(suzuki.engine_no)
print(suzuki.__dict__)

MYCar.cls_engine_no()

My car has silver Color and modal is 2019
1235555
1235555
1111111111
37777777
{'color': 'silver', 'modal': 2019, 'engine_no': 37777777}


333333333333

In [29]:
# staticmethod performs operations on external data(neither in class nor in object)
# it can also perform operations on static variable which is class variables

class Ubl:
    # class variable or static variable
    rate_of_interest = 5


    @staticmethod
    def calcuate_interest(p, i):# self or cls keywords are not used
        si = p * i * Ubl.rate_of_interest/100
        print(si)

Ubl.calcuate_interest(200000, 8) # static method only access class name with staticmethod

80000.0


In [28]:
class Employee:

    # setter method to set the instance variable
    def setName(self, name):
        self.name = name
    # getter method to get the value of instance variable
    def getName(self):
        print("my name is ", self.name)

e1:Employee = Employee()
e1.setName("saleem")# set the value 
e1.getName()

print(Employee.__dict__)

my name is  saleem
{'__module__': '__main__', 'setName': <function Employee.setName at 0x000001E029D8DC60>, 'getName': <function Employee.getName at 0x000001E029D8ECA0>, '__dict__': <attribute '__dict__' of 'Employee' objects>, '__weakref__': <attribute '__weakref__' of 'Employee' objects>, '__doc__': None}


# Inheritance

* for code reusability

In [35]:
# parent class
class Employee(object): # all classes are inherited by default fron object class
    bonus = 10000

    def display(self):
        print("this is a parent class method")

# child class has own variable and methods as well as parent class
class Manager(Employee):
    bonus1 = 5000

    def show(self):
        print("this is child class method")



e:Employee = Employee()
m:Manager = Manager()
print(m.bonus1)#child class variable
m.show()#child class method
print(m.bonus) # parent class variable is accessed by child class
m.display()#parent class nethod is accessed by child class

5000
this is child class method
10000
this is a parent class method


In [38]:
# constructor in parent class but not in child class

class Father:
    def __init__(self) -> None:
        print("father class constructor is called")
        self.vehicle = "Motorcycle"


# when child class has no constructor then father class constructor is called by default
class Son(Father):
    pass

son:Son = Son()

print(son.__dict__)

father class constructor is called
{'vehicle': 'Motorcycle'}


In [40]:
# constructor in parent class but also in child class
# constructor over-riding

class Father:
    def __init__(self) -> None:
        print("father class constructor is called")
        self.vehicle = "Motorcycle"


# when constructor is available in both classes  then child  class constructor is called
# the priority would be given to child class , first search into the child class if not avaialable then search into parent class
class Son(Father):
    def __init__(self) -> None:
        print("son class constructor is called")
        self.vehicle = "Bmw"

son:Son = Son()

print(son.__dict__)

son class constructor is called
{'vehicle': 'Bmw'}


In [43]:
# super() method
class Father:
    def __init__(self) -> None:
       self.bike = "Motorcycle"
       print("father class constructor is called")


class Son(Father):
    def __init__(self) -> None:
        super().__init__() # parent class properties are accessed by using super method
        print("son class constructor is called")
        self.vehicle = "Bmw"

son:Son = Son()

print(son.__dict__)

father class constructor is called
son class constructor is called
{'bike': 'Motorcycle', 'vehicle': 'Bmw'}


In [48]:
# super() method
class Father:
    def __init__(self, name, age) -> None:
       self.name = name
       self.age =age
       self.bike = "Motorcycle"
       print("father class constructor is called")


class Son(Father):
    def __init__(self) -> None:
        super().__init__("saleem", 21) # parent class properties are accessed by using super method
        print("son class constructor is called")
        self.vehicle = "Bmw"

son:Son = Son()

print(son.__dict__)

father class constructor is called
son class constructor is called
{'name': 'saleem', 'age': 21, 'bike': 'Motorcycle', 'vehicle': 'Bmw'}


In [46]:
# super() method
class Father:
    def __init__(self, name, age) -> None:
       self.name = name
       self.age =age
       self.bike = "Motorcycle"
       print("father class constructor is called")


class Son(Father):
    def __init__(self, name, age) -> None:
        super().__init__(name, age) # parent class properties are accessed by using super method
        print("son class constructor is called")
        self.vehicle = "Bmw"

son:Son = Son("saleem", 43)

print(son.__dict__)

father class constructor is called
son class constructor is called
{'name': 'saleem', 'age': 43, 'bike': 'Motorcycle', 'vehicle': 'Bmw'}


In [50]:
# super() method
class Father:
    def __init__(self, name, age) -> None:
       self.name = name
       self.age =age
       self.bike = "Motorcycle"
       print("father class constructor is called")

    def display(self):
        print("this is parent class method")


class Son(Father):
    def __init__(self) -> None:
        super().display() # parent class properties are accessed by using super method
        print("son class constructor is called")
        self.vehicle = "Bmw"

son:Son = Son()

print(son.__dict__)

this parent class method
son class constructor is called
{'vehicle': 'Bmw'}


In [ ]:
# single and multi-level inheritance
# single inheritance class contains one parent and one child class
            # object class ----> parent class -----> child class

In [51]:
# multi-level inheritance
#  object class ----> parent class -----> child class---> grandchild class

class Owner(object):
    salary = 12000

class Employee(Owner):
    salary = 2000

class Manager(Employee):
    salary = 1000


m:Manager = Manager()

m.salary

1000

In [53]:

class Owner(object):
    salary = 14000

class Employee(Owner):
    salary = 4000

class Manager(Employee):
    pass


m:Manager = Manager()

m.salary

4000

In [58]:
#  Hierarchical inheritance one parent class and multiple child classes


class Person:
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

    def display(self):
        print("this is a person class method")

# child class
class Employee(Person):
    def __init__(self, name, age, salary) -> None:
        super().__init__(name, age)
        self.salary = salary

    def display(self):
        print("this is a Employee class method")


# child class

class Manager(Person):
    def __init__(self, name, age, bonus) -> None:
        super().__init__(name, age)
        self.salary = bonus

    def display(self):
        print("this is a Manager class method")


e:Employee = Employee("saleem", 43, 3000000)
print(e.__dict__)
print("-------------------------")
m:Manager = Manager("saleem", 43, 5000000)
print(m.__dict__)

{'name': 'saleem', 'age': 43, 'salary': 3000000}
-------------------------
{'name': 'saleem', 'age': 43, 'salary': 5000000}


In [64]:
#  Multiple inheritance multiple parent class and one  child classes
class Person:
    def __init__(self) -> None:
        print(" this is person class const")
        self.name = "salemm"
       
class Employee():
    def __init__(self) -> None:
        super().__init__()
        print(" this is employee class const")
        self.name = "saram"

# child class

class Manager(Employee, Person):
    def __init__(self) -> None:
        super().__init__()
        print(" this is manager  class const")
        self.name= "hamza"

    def display(self):
        print("this is a Manager class method")


m:Manager = Manager()
print(m.__dict__)

 this is person class const
 this is employee class const
 this is manager  class const
{'name': 'hamza'}


In [1]:
# MRO(Method Resolution Order)       --inheritance
# how  properties are searched in inheritance

# classname.mro()


class A:
    pass

class B:
    pass
class C:
    pass

class X(A, B):
    pass
class Y(X, C):
    pass

print(Y.mro())

[<class '__main__.Y'>, <class '__main__.X'>, <class '__main__.A'>, <class '__main__.B'>, <class '__main__.C'>, <class 'object'>]


# Encapsulation
* Wrapping yp data and method in a single unit that is a class on performing operation on its data is called encapsulation

In [11]:
class Finance:
    def __init__(self):
        self.__revenue = 1000000 # make it private by using idenfier __private
        self.salary = 50000 # public variable
    
    def display(self):
        print(self.__revenue)

finance = Finance()
finance.salary # accessible everywhere due public variable 
#finance.__revenue #AttributeError: 'Finance' object has no attribute '__revenue'
finance.display() # now private property is accessible through method
print(finance.__dict__)
print(finance._Finance__revenue) # can be accessible by using "name mangling"

1000000
{'_Finance__revenue': 1000000, 'salary': 50000}
1000000


# polymorphism
 * python object has different behavior in differnt situation

In [19]:
# polymorphism in inheritance differnt behavior in different situation
class Veh:
    def __init__(self, name, color, price) -> None:
        self.name = name
        self.color = color
        self.price = price
    
    def get_detail(self):
        print(f"name is {self.name} and color is {self.color} and price is {self.price}")

    def max_speed(self):
        print("Max speed is 150Km/hr")


class Car(Veh):
    def max_speed(self):
        print("Max speed is 100Km/hr")


V1 = Veh("Truck", "black", 90000000000)
C1 = Car("suzuki", "white", 700000000)
V1.max_speed() # polymorphism in inheritance differnt behavior in different situation
C1.max_speed() # polymorphism in inheritance differnt behavior in different situation


Max speed is 150Km/hr


In [16]:
#  Over-riding built-in function

"""while executing print function it will call magic method __str__ 
first print(c1) will search in Cart class if not present then it call built-in library and 
it will give the output <__main__.Cart object at 0x000001A2CD575CD0>

it can by over-riding by defining in the class with same name and required output can be get printed

"""
class Cart:
    pass

c1 = Cart()

print(c1)

In [18]:
#  Over-riding built-in function

"""while executing print function it will call magic method __str__ 
first print(c1) will search in Cart class if not present then it call built-in library and 
it will give the output <__main__.Cart object at 0x000001A2CD575CD0>

it can by over-riding by defining in the class with same name and required output can be get printed

"""
class Cart:
    # Over-riding built-in function
    def __str__(self):
        return "this is cart obj"
c1 = Cart()
print(c1)

this is cart obj


In [21]:
  # polymorphism in function and object
class Veh:
    def __init__(self, name, color, price) -> None:
        self.name = name
        self.color = color
        self.price = price
    
    def get_detail(self):
        print(f"name is {self.name} and color is {self.color} and price is {self.price}")

    def max_speed(self):
        print("Max speed is 150Km/hr")


class Car(Veh):
    def max_speed(self):
        print("Max speed is 100Km/hr")



# outside the class , different behavior with differnt input
  # polymorphism in function and object
def get_output(obj):
    obj.max_speed()

V1 = Veh("Truck", "black", 90000000000)
C1 = Car("suzuki", "white", 700000000)
get_output(V1)
get_output(C1)


Max speed is 150Km/hr
Max speed is 100Km/hr


In [24]:
# Polymorphism    =======   Operator Overloading in Python

# + operator

num1 = 7
num2 = 9
print(num1 + num2)
print(num1.__add__(num2))
print(int.__add__(num1, num2))
# first check the datatype of left operand
# go to the class
# call the __add__ function

num1 = "hello"
num2 = "world"
print(num1 + num2)
print(num1.__add__(num2))
print(str.__add__(num1, num2))
# first check the datatype of left operand
# go to the class
# call the __add__ function

num1 = "hello"
num2 = 20
print(num1 + num2)
print(num1.__add__(num2))
print(str.__add__(num1, num2))
# first check the datatype of left operand
# go to the class
# call the __add__ function

16
16
16
helloworld
helloworld
helloworld


TypeError: can only concatenate str (not "int") to str

In [27]:
# How to achieve operator overloading

class Book:
    def __init__(self, name, pages) -> None:
        self.name = name
        self.pages = pages

    def __add__(self, other):
        total = self.pages + other.pages
        return total
    
    def __gt__(self, other): # (b1, b2)
        return self.pages > other.pages # retrun true or false

b1 = Book("one Intelligent girl", 600)
b2 = Book("othello", 400)
print("total pages:", b1.pages + b2.pages) # b1.__add__(b2) -->Book.__add__(b1, b2)

print("total pages:", b1+ b2) # trow type error , now declare add method to resolve this error

# comparison operator overloading

print(b1>b2) # give the type error because __gt__ method not found in the class hotel , will have to declare in the class

total pages: 1000
total pages: 1000
True


In [30]:
# How to achieve operator overloading

class Book:
    def __init__(self, name, pages) -> None:
        self.name = name
        self.pages = pages

    def __add__(self, other):
        total = self.pages + other.pages
        return Book("all books", total) # it will return this message total pages: <__main__.Book object at 0x000001A2CD573BF0>
    
    
    # total pages: <__main__.Book object at 0x000001A2CD573BF0> now it will return output 
    def __str__(self) -> str:
        return str(self.pages)
    def __gt__(self, other): # (b1, b2)
        return self.pages > other.pages # retrun true or false

b1 = Book("one Intelligent girl", 600)
b2 = Book("othello", 400)
b3 = Book("prince", 400)
print("total pages:", b1.pages + b2.pages) # b1.__add__(b2) -->Book.__add__(b1, b2)

print("total pages:", b1+ b2) # trow type error , now declare add method to resolve this error
print("total pages:", b1+ b2+ b3)
# comparison operator overloading

print(b1>b2) # give the type error because __gt__ method not found in the class hotel , will have to declare in the class

total pages: 1000
total pages: 1000
total pages: 1400
True


In [4]:
# Function over- loading in polymorphism
from typing import overload

@overload
def add(x:int, y:int)->int:
    ...

@overload
def add(x:str, y:str)->str:
    ...

@overload
def add(x:float, y:float)->float:
    ...

def add(x, y):
    return x + y
    


add(4, 8)


12

In [2]:
# Method over- loading in polymorphism


from typing import overload
class Addition:
    @overload
    def add(self, x:int, y:int)->int:
        ...
    @overload
    def add(self, x:str, y:str)->str:
        ...

    def add(self, x,  y):
        return x + y
    

cal:Addition = Addition()
print(cal.add(4, 8))
print(cal.add("4", "8"))

12
48


In [4]:
# Nested class

class Student:
    def __init__(self, name, roll_no, dd, mm, yy) -> None:
        self.name = name
        self.roll_no = roll_no
        self.dob = self.DOB(dd, mm, yy) # nested class Dob declared here as a variable
    def display(self):
        print(f"My name is {self.name} and roll number is {self.roll_no}")
        self.dob.display()# nested class display method  declared
    class DOB:
        def __init__(self, dd,mm,yy) -> None:
            self.dd = dd
            self.mm = mm
            self.yy = yy

        def display(self):
            print(f"Date of Birth is {self.dd}/{self.mm}/{self.yy}")

s1 = Student("saleem", 123, 9, 1, 1980)  

s1.display()

My name is saleem and roll number is 123
Date of Birth is 9/1/1980


In [6]:
# Accessing properties of one class into another class

class Student:
    def __init__(self, name, salary) -> None:
        self.name = name
        self.salary = salary

    def display(self):
        print(f" my name is {self.name} and my salary is {self.salary}")


class student2:
    # staticmethod decorator is used to play with external data 
    @staticmethod
    def display(obj):
        obj.salary = obj.salary + 20000022222
        obj.display()


s1= Student("salemm", 1239999999)

s2= student2()
s2.display(s1)

 my name is salemm and my salary is 21240022221


In [7]:
# Destructor ====   __del__
# it destroys the object and releases resorces tied to object
# it is called when refrence is zero and variables go out of scop
# it is automatically called when object is destroyed
'''when refrence is zero and variables go out of scop , 
Garbage collector comes into play to remove it from memory but before 
Garbage collector , destructor is called to release the tied resources with that object
'''
# Disadvantages of Destructor
''' Circular refrences ---when two object refer to each other.


'''

class Student:
    def __init__(self, name, salary) -> None:
        self.name = name
        self.salary = salary

    def display(self):
        print(f" my name is {self.name} and my salary is {self.salary}")
    # Destructor defining
    def __del__(self):
        print("destructor is called")


s1:Student = Student("sak", 11111111)
s1.display()

del s1

 my name is sak and my salary is 11111111
destructor is called


# Class Decorator

In [13]:
from typing import Any


class Decorator:
    def __init__(self, func) -> None:
        self.function = func
        
    def __call__(self, a, b) -> Any:
        result = self.function(a, b)
        return result**2
       
@Decorator
def add(a, b):
    return a + b
# d1 = Decorator(add)
print(add(2,7))


81


In [16]:
class Add(object):
    pass

a1 = Add()
print(callable(Add))
dir(add)

True


['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

# Abstraction
 * hiding complex implementation from user and only signatures are shown to user
 * the object of abstract class can not be made
 * interface --a abstract class in which all methods are abstract method and no concrete method

In [ ]:
from abc import ABC, abstractmethod

 # abstract class is inherited from ABC class and atleast one abstract method is required
class Car(ABC):
     # method only declare but no implementation is here , implementation must be in child class
    @abstractmethod 
    def mileage(self):
        pass

    def color(self):
        print("color is white")


class Suzuki(Car):

    def mileage(self):
        print("yhe mileage of suzuki is 400 km")
    

class Nissan(Car):
    # if abstract method of abstract class is not implemented in child class it becomes abstract class
    def mileage(self):
        print("yhe mileage of nissqan is 320 km")

class Mehran(Car):

    def mileage(self):
        print("yhe mileage of nissqan is 320 km")

suz:Car = Suzuki()
suz.color()
suz.mileage()

In [13]:



class NonCallable:

    def display(self, name):
        print(name)

    def __call__(self, f):
        display(f)
    
instance : NonCallable = NonCallable()
callable(instance)

instance("salrrr")

'salrrr'

In [4]:
class NonCallable:
    def __call__(self):
        raise TypeError("not really callable")

# Create an instance of NonCallable
instance: NonCallable = NonCallable()

# Check if the instance is callable
if callable(instance):
    try:
        # Attempt to call the instance
        instance()
    except TypeError as e:
        print(f"Caught an error: {e}")
else:
    print("Instance is not callable.")


Caught an error: not really callable


In [11]:
import numpy as np
a:np.ndarray = np.array([[1,2,3,3,3,8],
                        [1,2,3,3,3,8],
                        [1,2,3,3,3,8]])
a.itemsize

4

In [1]:
%pip install nptyping

Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy as np
from nptyping import NDArray, Shape, UInt64
from typing import Any
a:NDArray[Shape["10"],  Any] = np.arange(1,11)

type(a)
a.dtype
a.shape

(10,)

In [24]:
a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3)
print(a)
a : NDArray[Shape["Size, Size"],Any] = np.arange(5*6).reshape(3,10)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [56]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*3*3).reshape(5,3,3)

#print(a)
print(a[::4,::,::])
print("---------")
print(a[::4,0:2:,::])
print("---------")
print(a[::4,0:3:,1:3:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]
---------
[[[ 0  1  2]
  [ 3  4  5]]

 [[36 37 38]
  [39 40 41]]]
---------
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[37 38]
  [40 41]
  [43 44]]]
