# python Array

In [2]:
# python array

import sys

my_list= [20, 30, 49,59, "abc", True] # list stores different type of data
print(my_list[0:2])
my_list[0] = 100 # value can be modified
print(sys.getsizeof(my_list))# check the size of memory- sys mopdule is imported. operation is slower than numpy array
print(my_list) # Mathematical operations can be performed on numpy array but not on list
print(my_list*10) # it will concate 10 times byt not multiply indivual item of list

my_list3 = [[20, 30, 49], [2,3]] # it supports inhomogeneous item 
print(my_list3)

[20, 30]
104
[100, 30, 49, 59, 'abc', True]
[100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True, 100, 30, 49, 59, 'abc', True]
[[20, 30, 49], [2, 3]]


# NumpyArray

In [3]:

import numpy as np

my_list:np.ndarray = np.array([20, 30, 49]) # numparray stores similar data type \

my_list[0:4] # same slicing and indexing as on python list
my_list[0] = 100 # mutable and value can be assigned 
print(my_list.itemsize ) # check the size of memory , operation is more fast than python list
print(my_list)

my_list2:np.ndarray = np.array([20, 30, 49, "45", 2.7, True]) # multiple data type will convert into same data type as string
print(my_list2)

print(my_list/10) # Mathematical operations can be performed on numpy array but not on list
print(my_list*10) # Mathematical operations can be performed on numpy array but not on list

my_list3:np.ndarray = np.array([[20, 30, 49], [2,3,4]]) # it will take homogeneous item , same size
print(my_list3)
my_list3:np.ndarray = np.array([[20, 30, 49], [2,3]]) # it will take homogeneous item ,if   size is not same , will throw error
print(my_list3)

4
[100  30  49]
['20' '30' '49' '45' '2.7' 'True']
[10.   3.   4.9]
[1000  300  490]
[[20 30 49]
 [ 2  3  4]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Create Numpy NDArray

In [ ]:
# zero dimension array/scalar
import numpy as np
arr0 = np.array(4)
print(arr0)
print("dimension", arr0.ndim)

In [ ]:
# one dimension array/vector
import numpy as np
arr1 = np.array([1,3,3,3])
print(arr1)
print("dimension", arr1.ndim)

In [ ]:
# Two dimension array/Matrix
import numpy as np
arr2 = np.array([[1,3,3,3], [2,3,4,6]])
print(arr2)
print("dimension", arr2.ndim)

In [ ]:
# Three dimension array/Tensor
import numpy as np
arr2 = np.array([[[1,3,3,3], [2,3,4,6]]])
print(arr2)
print("dimension", arr2.ndim)

In [ ]:
## nth dimension array

import numpy as np
arr1 = np.array([1,3,3,3], ndmin=4)
print(arr1)
print("dimension", arr1.ndim)

In [ ]:
import numpy as np

n = int(input("Enter your Number"))

data = []
for i in range(n):
    value = int(input("enter your element"))
    data.append(value)
numdata= np.array(data)
print(numdata)
print(numdata.ndim)

In [ ]:
# properties of Numpy arry are ndim, size, itemsize, min(), max(),shape, sum(axis= 0 0r 1)

import numpy as np

arr1 = np.array([[1,4,6,7,7], [3,4,4,6,6], [3,5,7,8,9]])

print(arr1)
print("dimension :",arr1.ndim)
print("memory size:",arr1.itemsize , "bytes")# one item memory size in bytes
print("total items:",arr1.size)# total number of elements in array
print("total Memory:",arr1.itemsize * arr1.size, "bytes")# total number of elements in array
print("Min item",arr1.min())
print("Max item",arr1.max())
print(arr1)
print("size of array:", arr1.shape)
print("sum of all items is :", arr1.sum())
print("sum of columns is :", arr1.sum(axis=0)) # will move top to bottom and sum the coloumns
print("sum of rows is :", arr1.sum(axis=1)) # will move left to right and sum the coloumns

In [ ]:
import numpy as np


my_arr = np.zeros((2,4), dtype="int64")
print(my_arr)
print(my_arr.shape)
print(my_arr.ndim)
print(my_arr.dtype)

In [ ]:
import numpy as np


my_arr = np.ones((2,4))*3
print(my_arr)
print(my_arr.shape)
print(my_arr.ndim)
print(my_arr.dtype)

In [ ]:
import numpy as np


my_arr = np.ones((2,4), dtype=[('x', 'int') , ('y', 'int')])
print(my_arr)
print(my_arr.shape)
print(my_arr.ndim)
print(my_arr.dtype)

In [68]:
# range function in numpy is ===arange()
import numpy as np
arr7 = np.arange(1,12, 3)
arr7

array([ 1,  4,  7, 10])

In [69]:
# linspace function wil;l provide 6 values between 1 to 12
import numpy as np
arr7 = np.linspace(1,12, 6)# it will provide linear space , 
arr7

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [ ]:
import numpy as np

arr = np.matrix([[1,2,3],[5,6,7]])
print(arr)
print(arr.shape)
arr1 = arr.T
print(arr1)
print(arr1.shape)

In [ ]:
print( np.eye(3, dtype="int"))

In [ ]:
print(np.diag([23,34,45]))

# Creating array with random Module

In [ ]:
# uniform distribution with random() and rand() functions
import numpy as np
arr = np.random.random()# random number
print(arr)


arr = np.random.random(3)# takes tuple and int
print(arr)

arr = np.random.random((2,2)) # takes tuple and int
print(arr)

arr = np.random.rand() # random number
print(arr)
arr = np.random.rand(2,3) # pass shape directly
print(arr)

print("----------------------------------------")

# Normal distribution , always give values around mean

arr = np.random.randn() # random value
print(arr)

arr = np.random.randn(3,3) # pass shape directly
print(arr)


In [ ]:
arr = np.random.randint(10)# atleast one value is required ; low value
print(arr)
print("-----------------------")
arr = np.random.randint(10, 20)# [low , high)
print(arr)
print("-----------------------")
arr = np.random.randint(10, 20, (3,3))# ([low , high) ,shape)
print(arr)
print("-----------------------")
arr = np.random.randint(10, 20, (3,3), dtype="int32")# ([low , high) ,shape, dtype)
print(arr)

In [ ]:
import numpy as np

np.random.choice([1,2,3,4], size= (2, 2), p=[0.1, 0.2, 0.0, 0.7])


In [ ]:
import numpy as np
#np.random.seed(111)
arr= np.array([1,2,3,4])
print(arr)
np.random.shuffle(arr)
print(arr)


In [ ]:
import numpy as np

arr= np.array([4,2,5,7])
print(arr)
np.random.permutation(arr)
print(arr)

# Lecture 16

In [ ]:
#%pip install nptyping beartype --upgrade --force

# scalar

In [ ]:
import numpy as np

a:np.ndarray = np.array(1000)
display(a)
display(type(a))
display(a.ndim)
display(a.shape)
display(a.dtype)
display(a.size)
display(a.itemsize)



# vector

In [ ]:
import numpy as np

a:np.ndarray = np.array([1,3,5,6,7,8])
display(a)
display(type(a))
display(a.ndim)
display(a.shape)
display(a.dtype)
display(a.size)
display(a.itemsize )
display(a.itemsize * a.size )


# Numpy with NDArray typing support

In [17]:
from nptyping import Int, NDArray, Shape , UInt64
from typing import Any

data: NDArray[Shape["2"], Any] = np.arange(1,11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [70]:
from nptyping import Int, NDArray, Shape
import numpy as np

shape = (2, 5)  # Define the shape as a tuple
data: NDArray[Shape["Size"], Any] = np.arange(1, 11).reshape(2, 5)
print(data)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [67]:
from nptyping import Int32, NDArray, Shape , UInt64
from typing import Any

data1: NDArray[Shape['10'], Int32] = np.arange(1,11)
print(data1)

data = np.arange(1,11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [71]:

from nptyping import Bool

state_bank:NDArray[Shape["10"], Any] = np.array([1,3,4,6,8,10])

select:NDArray[Shape["10"], Bool] = np.array([False,False,True,False,False,True])
state_bank[select]


array([ 4, 10])

In [72]:

from nptyping import Bool

state_bank:NDArray[Shape["10"], Any] = np.array([1,3,4,6,8,10])


state_bank[state_bank % 2 == 0]


array([ 4,  6,  8, 10])

# in1d

In [85]:
state_bank:NDArray[Shape["10"], Any] = np.array([1,3,4,6,8,10])

ubl_bank:NDArray[Shape["20"], Any] = np.random.randint(1,80, 20)

np.in1d(state_bank, ubl_bank)


array([False, False, False,  True, False, False])

In [106]:
# intersect1d

state_bank:NDArray[Shape["10"], Any] = np.array([1,3,4,6,8,10])

ubl_bank:NDArray[Shape["20"], Any] = np.random.randint(1,80, 20)

np.intersect1d(state_bank, ubl_bank)


array([], dtype=int32)

In [110]:
x:NDArray[Shape["6"], Any] = np.array([1,3,4,6,9,10])

y:NDArray[Shape["6"], Any] = np.array([7,6,4,8,8,10])

np.where(x>y, x, y)

array([ 7,  6,  4,  8,  9, 10])

In [114]:
x:NDArray[Shape["Size, Size"], Any] = np.array([[1,3,4],
                                                [6,9,10]])



y:NDArray[Shape["Size, Size"], Any] = np.array([[7,6,4,8], 
                                                [8,10,4,5]])


print(x)
print("-------------------------------")
print(y)
print("-------------------------------")

[[ 1  3  4]
 [ 6  9 10]]
-------------------------------
[[ 7  6  4  8]
 [ 8 10  4  5]]


In [116]:
x:NDArray[Shape["Size, Size"], Any] = np.arange(3*3).reshape(3,3)



y:NDArray[Shape["Size, Size, Size"], Any] = np.arange(2*3*3).reshape(2,3,3)


print(x)
print("-------------------------------")
print(y)
print("-------------------------------")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
-------------------------------


In [155]:
x:NDArray[Shape["Size, Size, Size"], Any] = np.arange(2*3*3).reshape(2,3,3)



y:NDArray[Shape["Size, Size, Size"], Any] = np.arange(3*3*3).reshape(3,3,3)


print(x)
print("-------------------------------")
print(y)
print("-------------------------------")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
-------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
-------------------------------


In [161]:
print(y[::,::,::])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [178]:
#         1      2      3
print(y[0:2:1, 0:2:1, 0:1:1])

# 1step -- will slice from all arrays 
# 2.    --- will slice rows from all arrays
# 3.   ----will slice coloumns from all arrays 

[[[ 0]
  [ 3]]

 [[ 9]
  [12]]]
